# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 14:43
from __future__ import unicode_literals

import application.apps.pages.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'contact',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GenericPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.wagtailcore.fields.StreamField((('quote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(application.apps.pages.models.Quote)),))), ('carousel', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(max_length=64)), ('subtitle', wagtail.wagtailcore.blocks.CharBlock(max_length=128)), ('slides', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('caption', wagtail.wagtailcore.blocks.CharBlock(max_length=32)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())))))))), ('cta', wagtail.wagtailcore.blocks.StructBlock((('call_to_action', wagtail.wagtailcore.blocks.CharBlock(max_length=32)), ('page', wagtail.wagtailcore.blocks.PageChooserBlock())))), ('banners', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(max_length=64)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()))), icon='fa-picture-o', template='blocks/banners.html'))))),
            ],
            options={
                'verbose_name': 'generic',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content_top', wagtail.wagtailcore.fields.StreamField((('demo', wagtail.wagtailcore.blocks.StructBlock((('is_cool', wagtail.wagtailcore.blocks.BooleanBlock()),), template='blocks/demo.html')),))),
                ('content', wagtail.wagtailcore.fields.StreamField((('carousel', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(max_length=64)), ('subtitle', wagtail.wagtailcore.blocks.CharBlock(max_length=128)), ('slides', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('caption', wagtail.wagtailcore.blocks.CharBlock(max_length=32)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())))))))), ('cta', wagtail.wagtailcore.blocks.StructBlock((('call_to_action', wagtail.wagtailcore.blocks.CharBlock(max_length=32)), ('page', wagtail.wagtailcore.blocks.PageChooserBlock()))))))),
            ],
            options={
                'verbose_name': 'home',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=128)),
            ],
        ),
    ]
